### PR TITLE
Fix scrolling if Form builder is not at the top of the page. 

### PR DESCRIPTION
**Pull request by rposborne**
All this does is calculates the scrolls position based upon the container.  Instead of just assuming the distance to the top of the page = the top of the form builder.

### CODE REVIEW

**Comment by ajb** [comment]
Thanks for the PR. I'll test this out and hopefully merge shortly.

**Comment by rposborne** [comment]
Don't worry got more coming :smile:

**Comment by ajb** [comment]
Thanks! Merged :star2:

**Comment by smurfpandey** [comment]
Why not use position: fixed on fb-left class? I am facing weird issues with this code. If I add a new component the left-side box's margin-top is set to a value which is  too high. Clicking again on the "Add Field" fixes the issue.
formbuilder position

If I comment the scrollEvent and set position as fixed, it work just fine.

**Pull request merged**
